#!/usr/bin/env python3


"""

Task 6 for lesson 01

"""


import locale

# check the default encoding in OS

default_encoding = locale.getpreferredencoding()

print("Default encoding in OS: {0}".format(default_encoding))
print("\n")
print("-"*40)
print("\n")

# create file with name test_file.txt and write some info inside

with open('test_file.txt','w') as test_file:
    
    text = "сетевое программирование, сокет, декоратор"
    test_file.writelines(text)
    
# read info from file

print("\n")
    
with open('test_file.txt', encoding='UTF-8', mode='r') as test_file:
    
    
    
    for text in test_file:
        
        print("Type of text inside file: {0}".format(type(text)))
        print("Text inside inthis file: \n{0}".format(text))
    
    
    

