#!/usr/bin/env python3

"""
 
Task number 1 from lesson 01
 
"""


""" 

Define variables with next words: разработка, сокет, декорптор.

"""

design_word = "разработка"

socet_word = "сокет"

decorator_word = "декоратор"


""" 

Convert standart char type into unicode format using online convertor 

"""

unicode_design_word = u"\u0440\u0430\u0437\u0440\u0430\u0431\u043E\u0442\u043A\u0430"

unicode_socet_word = u"\u0441\u043E\u043A\u0435\u0442"

unicode_decorator_word = u"\u0434\u0435\u043A\u043E\u0440\u0430\u0442\u043E\u0440"


""" 

Compare variables which include standart char type value and with unicode

""" 

print("Variables with standard char type values:\n")
print("Type of design_word, socet_word, decorator_word variables: \n{0},{1},{2}".format(type(design_word), type(socet_word), type(decorator_word)))
print("-"*30)
print("Values of design_word, socet_word, decorator_word variables: \n{0}\n{1}\n{2}".format(design_word, socet_word, decorator_word))
print("\n")
print("Variables with unicode type values:\n")
print("Type of design, socet, decorator variables: \n{0}\n{1}\n{2}".format(type(unicode_design_word), type(unicode_socet_word), type(unicode_decorator_word)))
print("-"*30)
print("Values of unicode_design_word, unicode_socet_word, unicode_decorator_word variables: \n\n{0}\n{1}\n{2}".format(unicode_design_word, unicode_socet_word, unicode_decorator_word))
