#!/usr/bin/env python3


"""

Task 4 for lesson 01

"""

# Define variables with string type valuse

design_word = "разработка"

administrating_word = "администрирование"

protocol_word = "protocol"

standard_word = "standard"

# Encode string 

design_word = design_word.encode('UTF-8', 'strict')

administrating_word  = administrating_word.encode('UTF-8', 'strict')

protocol_word = protocol_word.encode('UTF-8', 'strict')

standard_word = standard_word.encode('UTF-8', 'strict')

# Show type of values in our variables aftero encode in byte type operation

print("Type of oue variables after encode operation: \n{0}\n{1}\n{2}\n{3}".format(type(design_word),type(administrating_word),type(protocol_word),type(standard_word)))

# Decode string

design_word = design_word.decode('UTF-8', 'strict')

administrating_word  = administrating_word.decode('UTF-8', 'strict')

protocol_word = protocol_word.decode('UTF-8', 'strict')

standard_word = standard_word.decode('UTF-8', 'strict')

# Show type of values in our variables aftero decode in string type operation

print("\n")
print("-"*40)

print("Type of oue variables after decode operation: \n{0}\n{1}\n{2}\n{3}".format(type(design_word),type(administrating_word),type(protocol_word),type(standard_word)))


