#!/usr/bin/env python3

"""
 
Task number 2 from lesson 01
 
"""

#import sys module for get info about variable length

import sys




""" 

Define variables with next words: class, function, method.

"""

class_word = b'class'

function_word = b'function'

method_word = b'method'


print("Type of value in class_word, function_word, method_word variables: \n{0},\n{1}, \n{2}".format(type(class_word),type(function_word),type(method_word)))
print("\n")
print("-"*40)
print("Vaules of class_word, function_word, method_word variables: \n{0}, \n{1}, \n{2}".format(class_word,function_word,method_word))
print("\n")
print("-"*40)
print("Length(size) of class_word, function_word, method_word variables in bytes: \n{0}, \n{1}, \n{2}".format(sys.getsizeof(class_word),sys.getsizeof(function_word),sys.getsizeof(method_word)))